[build]
  publish = "." # Publish the root directory
  command = "echo 'No build command needed for this static site'"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
